language: java

script: "mvn deploy --settings travis/settings.xml"

jdk:
  - oraclejdk7

env:
  global:
  - secure: "SGO9NiZHdPlAwm9qHirXz5lCx1462Ch/MgvKK9TGJDzsmea414TRucHCmL17a+shsLtt/iXE4whikKBcTY4b493wtXYbC5EzZrVb5QKA1XEdjfgbnESov6DLVS85waO/K0GBScmyu02YOC/0ZCShcXrQZpJ0ssK9eMM/jXdTLsQ="
  - secure: "CPVVDE6VYWZC6EuMpTx+FitoKhC5nAxjFHOWJ8g20dRu5syNRmtYLXJP7wj7xBiDHTF52LIE86d9NHppt/VZwNXXjo0BUQoAl+W8m0n08QsWTfmUO5IXQQjQXMAWt4QQ13ON4fHmxVQDRlgQFmcqyXO1yWdcAngWXBK+pJh7zWU="

